//! Completed items in the Mage category.

items! {
    banshees_veil,
    blackfire_torch,
    bloodletters_curse,
    cosmic_drive,
    dusk_and_dawn,
    grezs_spectral_lantern,
    hextech_gunblade,
    lich_bane,
    liandrys_torment,
    malignance,
    morellonomicon,
    nashors_tooth,
    night_harvester,
    rabadons_deathcap,
    riftmaker,
    rite_of_ruin,
    rod_of_ages,
    rylais_crystal_scepter,
    shadowflame,
    stormsurge,
    void_staff,
    zhonyas_hourglass,
}
