// The six legendary classes, in picker order. The picker also has a `Boots`
// group, which [`category_rank`] sorts after these; it is left out of this
// array because the Item Stats tab builds one filter row per entry.
pub const CATEGORY_ORDER: [&str; 6] =
    ["Assassin", "Fighter", "Marksman", "Mage", "Tank", "Support"];

// Every item's class, generated by build.rs from `text/item_classes.json` -
// the one place a class is written down. The file also ships with the mod:
// `item_scroller_tfm2` reads it to class this pack's items in its filter, so a
// new item goes in the file and nowhere else.
include!(concat!(env!("OUT_DIR"), "/item_classes.rs"));

const fn str_eq(a: &str, b: &str) -> bool {
    let (a, b) = (a.as_bytes(), b.as_bytes());
    if a.len() != b.len() {
        return false;
    }
    let mut i = 0;
    while i < a.len() {
        if a[i] != b[i] {
            return false;
        }
        i += 1;
    }
    true
}

// A class the picker does not know would sort after Boots and match no Item
// Stats filter row, so a typo in the file stops the build instead.
const _: () = {
    let mut i = 0;
    while i < CATEGORY_OF.len() {
        let class = CATEGORY_OF[i].1;
        let mut known = str_eq(class, "Boots");
        let mut j = 0;
        while j < CATEGORY_ORDER.len() {
            known |= str_eq(class, CATEGORY_ORDER[j]);
            j += 1;
        }
        assert!(
            known,
            "text/item_classes.json names a class that is not Boots or in CATEGORY_ORDER"
        );
        i += 1;
    }
};

const RESKIN_ICON: &[(&str, &str)] = &[
    ("bloodthirster", "t4_0"),
    ("dragons_claw", "t4_3"),
    ("ludens_tempest", "t4_4"),
    ("phantom_dancer", "t4_1"),
    ("sunfire_cape", "t4_5"),
    ("thornmail", "t4_2"),
];

pub fn icon_frame(slug: &str, is_mod_item: bool) -> Option<&str> {
    if let Ok(index) = RESKIN_ICON.binary_search_by_key(&slug, |(key, _)| key) {
        return Some(RESKIN_ICON[index].1);
    }
    is_mod_item.then_some(slug)
}

pub fn category_of(slug: &str) -> Option<&'static str> {
    CATEGORY_OF
        .binary_search_by_key(&slug, |(key, _)| key)
        .ok()
        .map(|index| CATEGORY_OF[index].1)
}

pub fn category_rank(category: &str) -> usize {
    CATEGORY_ORDER
        .iter()
        .position(|name| *name == category)
        .unwrap_or(CATEGORY_ORDER.len())
}
