//! Tier-2 components: the parts that build into the completed items.

items! {
    aegis_of_the_legion,
    bandleglass_mirror,
    bf_sword,
    blighting_jewel,
    caulfields_warhammer,
    executioners_calling,
    fated_ashes,
    forbidden_idol,
    glacial_buckler,
    glowing_mote,
    haunting_guise,
    hextech_alternator,
    hearthbound_axe,
    last_whisper,
    needlessly_large_rod,
    noonquiver,
    oblivion_orb,
    phage,
    scouts_slingshot,
    serrated_dirk,
    sheen,
    steel_sigil,
    winged_moonplate,
}
