//! Tier-2 components: the parts that build into the completed items.

items! {
    aegis_of_the_legion,
    bamis_cinder,
    bandleglass_mirror,
    bf_sword,
    blighting_jewel,
    bounty_of_worlds,
    caulfields_warhammer,
    executioners_calling,
    fated_ashes,
    forbidden_idol,
    glacial_buckler,
    glowing_mote,
    haunting_guise,
    hextech_alternator,
    hearthbound_axe,
    last_whisper,
    needlessly_large_rod,
    noonquiver,
    oblivion_orb,
    phage,
    runic_compass,
    scouts_slingshot,
    seekers_armguard,
    serrated_dirk,
    sheen,
    spirit_stone,
    steel_sigil,
    tiamat,
    verdant_barrier,
    winged_moonplate,
    world_atlas,
}
